name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  crypto: ^3.0.7
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  intl: ^0.20.2
  animations: ^2.1.1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env